### ISSUE TITLE
code gets stuck in com_readSerialPort() function 

### ISSUE THREAD

**Issue by hassin23ayz** [Gurux/GuruxDLMS.c#1]
In Arduino Client.ino sketch example the code does not exit from com_readSerialPort() function.

**Comment by gurux01** [comment]
Hi,

This is a simple example. If meter don't reply data client wait here. We'll improve example to handle wait time.

**Comment by hassin23ayz** [comment]
Meter replied UA to the SNRM but the library can't handle the UA frame . debugging deep into the library i found that the code gets failed at dlms_getHDLCAddress() function of dlms.c file at the following section 
------------------------------------------------------------------------------------------------
    //DLMS CCT test requires that client size is one byte.
    if (isClientAddress && size != 1)
    {
        return DLMS_ERROR_CODE_INVALID_CLIENT_ADDRESS;
    }
------------------------------------------------------------------------------------------------
The UA was 
0x7E 0xA0 0x21 0x5 0x2 0x21 0x73 0x80 0xBC 0x81 0x80 0x14 0x5 0x2 0x1 0x0 0x6 0x2 0x1 0x0 0x7 0x4 0x0 0x0 0x0 0x1 0x8 0x4 0x0 0x0 0x0 0x1 0x69 0x6D 0x7E

**Comment by gurux01** [comment]
Your client and meter address are in the wrong order. Swap them to the DLMS client.
